# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e8b0391c8852cafe5da92a2ca421cff7045e2052fe69dd78804b1430f96ab6b776d598813f3abb0f21aacb50ed41a2402185806010374b6710f6ea600b5c7894

test:
  secret_key_base: e73152c1674562066172e7a05815dcbf4c7acfabe58da402af22776ff3ad9e9ee6ae0494eea6aca4b9d3193160e1a0589d610ca0bd4035bf96e36bb691ef350d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
